# 黑名单字符配置
# 格式：bad.chars=字符1,字符2,字符3,...
bad:
  chars: 老,谄,怅,娈,吊,不,戍,戎,昏,逐,刑,我,丑,谑,怒,氓,搔,怕,稗,谗,戚,逝,鸟,堠,吠,倡,鸡,瘥,否,瘦,丧,砧,怨,谪,爪,鸭,戮,谮,鸱,瘴,父,尸,落,血,鹅,婆,呆,蹇,晏,虏,鹑,婚,乞,桧,恨,汩,恫,灭,灰,乱,虱,牲,穴,偷,恸,豺,鱼,灾,驿,窃,邅,肉,蚊,亏,碑,墓,蚓,悔,麕,溘,墙,媚,窜,芜,媟,废,亡,碣,蚤,窥,邪,劫,犬,悲,暴,亵,悸,悼,咽,难,蒿,哀,狂,烂,仃,狄,蛆,仇,蛇,嫉,惊,狐,黔,胔,狗,惘,棘,囚,狡,泣,苦,惨,惩,泪,烬,独,更,壶,零,胸,狸,狼,哽,烽,勿,愁,漏,弗,优,缟,欠,素,鼠,鬣,败,茨,未,匪,贬,夭,蜮,伶,缺,贼,鬼,朽,放,祀,杀,魅,荆,蝇,浇,魉,半,魍,蝎,孑,魑,酒,单,孕,卜,畜,佞,非,坟,奠,靡,孤,饥,潦,罪,祭,赭,筮,蝱,女,罴,奸,祸,死,祼,兽,徂,殂,螂,殃,玄,殇,妇,醉,残,鞋,羌,垒,妒,殒,妓,殓,憔,辕,妖,禘,疚,羞,疠,莠,殡,冢,疢,薨,莫,枭,枯,辱,害,妹,禽,螽,妾,疾,蟀,迁,寂,凄,病,蟆,寇,駉,蟊,凋,毋,觋,蟋,痌,母,懒,痒,痗,俘,叛,痛,毛,诛,柝,寞,无,寡,寥,燧,只,巫,淫,凶,秽
